# Generated by Django 4.1.5 on 2023-02-03 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Nebulosa', 'Nebulosa'), ('Estrela', 'Estrela'), ('Galáxia', 'Galáxia'), ('Planeta', 'Planeta')], default='', max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.CharField(max_length=100)),
                ('publicada', models.BooleanField(default=False)),
                ('data_fotografia', models.DateTimeField(default=datetime.datetime)),
            ],
        ),
    ]
